### PR TITLE
Fix idempotence in windows-feature.yml

### PR DESCRIPTION
**Pull request by stefanDeveloper**
As stated in the annotation, I added the idempotent for the DISM state of a feature.

### CODE REVIEW

**Comment by juju4** [comment]
Thanks @stefanDeveloper 
Can you confirm if you tested this only on English Windows or more?
as marked in comment, the text output seems localized meaning string to detect depend on windows language.
Not sure if way to force English like in linux with LANG=C.

**Comment by stefanDeveloper** [comment]
I've tested it on English and German, however, as you have mentioned, the strings a local depended.
So `Status : Deactivated` is in German `Status : Deaktiviert`, same goes for `The operation completed successfully.`. On a German machine the string is `Der Vorgang wurde erfolgreich beendet.`.
I've seen this issue in the whole role and fixed it on my fork so it works with my machines. I could deliver a separate pull request for that.

In general, what you could do is to retrieve the system language and load depend on that the strings, like so: 

```yaml
- name: Get system language # would return en-EN or de-DE
  ansible.windows.win_powershell:
    script: |
      (Get-CimInstance -ClassName Win32_OperatingSystem).MUILanguages | Select-Object -Index 0 
  register: system_language
  tags: get_system_language

- name: Include language-specific variables.
  include_vars: "{{ system_language }}.yml"
  ```

Other users could add their system specific variables then.

**Comment by juju4** [comment]
That would be great! Thanks a lot!

**Comment by stefanDeveloper** [comment]
@juju4 Sry it took me some time to add this feature. I've added it now and it is ready for review

**Comment by juju4** [comment]
Looks great! Thanks a lot!

**Comment by juju4** [comment]
can you fix the lint part? yamllint, maybe ansible-lint.
other CI are broken for now

**Comment by stefanDeveloper** [comment]
Yes, I'll fix the linting!

**Comment by juju4** [comment]
Thanks!

**Pull request merged**
